### ISSUE TITLE
fix references

### ISSUE THREAD

**Issue by lottybrand** [lottybrand/Clickbot_analysis#3]

**Comment by tomstafford** [comment]
What needs fixing?

**Comment by lottybrand** [comment]
think it's probably just me /zotero not getting the right bibtx format. I'm starting to think using zotero with rmkardown might *actually* be slower than just your archaic meditative strategy of copy pasting from GoogSchol!

**Comment by lottybrand** [comment]
think I've fixed these now but probably still need more refs in places
